title: NodeSchool DÃ¼sseldorf
description: ""
url: "http://nodeschool.io/duesseldorf"
collections:
  events:
    output: true
    permalink: /:path
last: 2

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
